// src/pages/Cart.jsx
import React, { useState } from 'react';
import { API } from '../config/api';
import { Link, useNavigate } from 'react-router-dom';
import { useCart } from '../context/CartContext';
import { Trash2, Plus, Minus, ArrowRight, MessageSquare, ShieldCheck } from 'lucide-react';

export default function Cart() {
  const { cart, updateQuantity, removeFromCart, getCartTotal, clearCart } = useCart();
  const navigate = useNavigate();
  const [formData, setFormData] = useState({ name: '', phone: '', location: '', notes: '' });
  const [isSubmitting, setIsSubmitting] = useState(false);

  const formatToKwacha = (amount) => {
    return 'MK ' + amount.toLocaleString('en-US', {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    });
  };

  const handleInputChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmitOrder = async (e) => {
    e.preventDefault();
    if (cart.length === 0) return;

    setIsSubmitting(true);
    try {
      // 1. Send the Order to your Backend API to save it in PostgreSQL/Neon database
      const response = await fetch(`${API}/orders`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          customer_name: formData.name,
          phone: formData.phone,
          delivery_location: formData.location,
          notes: formData.notes,
          items: cart.map(item => ({
            id: item.id,
            quantity: item.quantity,
            price: parseFloat(String(item.price).replace(/[^0-9.]/g, ''))
          })),
          total_price: getCartTotal()
        })
      });

      const result = await response.json();
      
      if (result.success) {
        const orderId = result.data.order_id; // Unique order reference generated by backend
        const orderTrackingUrl = `${window.location.origin}/track-order?orderId=${orderId}`;

        // 2. Format a professional invoice structured for WhatsApp
        const WHATSAPP_NUMBER = "265995727978"; // Your WhatsApp number
        const itemsList = cart.map(item => `• ${item.quantity}x ${item.name} (${item.price})`).join('\n');
        
      const message = 
                
                `Hi! I'd like to confirm availability for this order:\n\n` +
                `*Order ID:* #${orderId}\n` +
                
                `*Selected Items:*\n${itemsList}\n` +
                `-----------------------------\n` +
                `*Estimated Total:* ${formatToKwacha(getCartTotal())}\n\n` 
        clearCart();

        // 4. Redirect to WhatsApp API and push user to Order Tracking page
        window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`, '_blank');
        navigate(`/track-order?orderId=${orderId}`);
      } else {
        alert("Failed to submit the order in database. Try again.");
      }
    } catch (err) {
      console.error("Order Checkout Error:", err);
      alert("Something went wrong connecting to the database server.");
    } finally {
      setIsSubmitting(false);
    }
  };

  if (cart.length === 0) {
    return (
      <div className="min-h-[70vh] bg-lightBg py-16 flex flex-col items-center justify-center px-4">
        <div className="bg-white p-8 rounded-2xl border border-slate-100 shadow-premium max-w-md w-full text-center">
          <h2 className="font-heading font-bold text-2xl text-slate-900 mb-2">Your basket is empty</h2>
          <p className="text-slate-500 text-sm mb-8">Browse the Resource Index to find and allocate premium assets.</p>
          <Link to="/catalog" className="inline-flex items-center gap-2 bg-primary hover:bg-slate-800 text-white font-heading font-bold text-sm px-6 py-3 rounded-xl transition-all">
            Return to Index <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-lightBg py-12 px-4 sm:px-6 lg:px-8 text-left">
      <div className="max-w-7xl mx-auto">
        <h1 className="font-heading font-bold text-3xl tracking-tight text-primary mb-8">Asset Allocation Checkout</h1>
        
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          {/* Left Column: Cart items */}
          <div className="lg:col-span-7 flex flex-col gap-4">
            {cart.map((item) => (
              <div key={item.id} className="bg-white p-4 rounded-xl border border-slate-100 shadow-sm flex gap-4 items-center">
                <img src={item.imageUrl} alt={item.name} className="w-16 h-16 object-cover rounded-lg bg-lightBg" />
                <div className="flex-grow">
                  <h4 className="font-heading font-bold text-sm text-slate-900 line-clamp-1">{item.name}</h4>
                  <p className="text-slate-500 text-xs font-semibold">{item.price}</p>
                </div>
                <div className="flex items-center gap-2 bg-lightBg rounded-lg p-1 border border-slate-200/50">
                  <button onClick={() => updateQuantity(item.id, item.quantity - 1)} className="p-1 text-slate-500 hover:text-primary transition-all"><Minus className="w-3.5 h-3.5" /></button>
                  <span className="text-xs font-semibold px-2">{item.quantity}</span>
                  <button onClick={() => updateQuantity(item.id, item.quantity + 1)} className="p-1 text-slate-500 hover:text-primary transition-all"><Plus className="w-3.5 h-3.5" /></button>
                </div>
                <button onClick={() => removeFromCart(item.id)} className="p-2 text-slate-400 hover:text-red-500 transition-colors"><Trash2 className="w-4 h-4" /></button>
              </div>
            ))}
          </div>

          {/* Right Column: Information Forms */}
          <div className="lg:col-span-5 bg-white p-6 rounded-2xl border border-slate-100 shadow-premium">
            <h3 className="font-heading font-bold text-lg text-slate-900 mb-6">Delivery details</h3>
            <form onSubmit={handleSubmitOrder} className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Recipient Name</label>
                <input required type="text" name="name" value={formData.name} onChange={handleInputChange} className="w-full px-4 py-3 bg-lightBg rounded-xl border border-transparent focus:border-slate-200 focus:bg-white text-sm outline-none transition-all" placeholder="Enter full name" />
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Phone Line (Airtel / TNM)</label>
                <input required type="text" name="phone" value={formData.phone} onChange={handleInputChange} className="w-full px-4 py-3 bg-lightBg rounded-xl border border-transparent focus:border-slate-200 focus:bg-white text-sm outline-none transition-all" placeholder="e.g. 0888123456" />
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Delivery Destination</label>
                <input required type="text" name="location" value={formData.location} onChange={handleInputChange} className="w-full px-4 py-3 bg-lightBg rounded-xl border border-transparent focus:border-slate-200 focus:bg-white text-sm outline-none transition-all" placeholder="e.g. Mzuzu / Lilongwe / Blantyre" />
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Special Directives (Optional)</label>
                <textarea rows="2" name="notes" value={formData.notes} onChange={handleInputChange} className="w-full px-4 py-3 bg-lightBg rounded-xl border border-transparent focus:border-slate-200 focus:bg-white text-sm outline-none transition-all resize-none" placeholder="Provide extra delivery coordinates..." />
              </div>

              <div className="pt-4 border-t border-slate-100">
                <div className="flex justify-between items-center mb-4">
                  <span className="text-sm font-semibold text-slate-500">Subtotal Amount:</span>
                  <span className="text-xl font-bold text-slate-900">{formatToKwacha(getCartTotal())}</span>
                </div>
                <button type="submit" disabled={isSubmitting} className="w-full bg-primary hover:bg-slate-800 disabled:bg-slate-400 text-white font-heading font-bold text-sm py-4 rounded-xl shadow-md transition-all flex items-center justify-center gap-2">
                  <MessageSquare className="w-4 h-4" /> {isSubmitting ? "Processing Order..." : "Confirm & Send to WhatsApp"}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}